apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: gha-runner-egress
spec:
  podSelector:
    matchLabels:
      {{- toYaml .Values.runnerLabels | nindent 6 }}
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: istio-system
      podSelector:
        matchLabels:
          istio: egressgateway
    ports:
    - port: 443
      protocol: TCP
